### ISSUE TITLE
Extended slayer.io.read_2d_spikes for bigger datasets

### ISSUE THREAD

**Issue by alexggener** [lava-nc/lava-dl#162]
### User story
Hi all. 

Slayer provides a nice set of tools for opening and visualize event datasets based on N-MNIST. I've been playing around with a DVS camera and tried to save the dataset in the same format to be able to use the io library LAVA-DL provides. However, I've notice that the N-MNIST dataset uses only 40 bit for each event, which reduces a lot its use for bigger frame resolution or sample times. For that reason, I propose to use the same structure (since it reduces a lot event dataset sizes) but using 96 bits per event with the following distribution: 
    #     bit 96 - 81: Xaddress (in pixels) 16bits
    #     bit 80 - 65: Yaddress (in pixels) 16bits
    #     bit 64: Polarity (0 for OFF, 1 for ON) 1bit
    #     bit 63 - 0: Timestamp (in microseconds) 64bits
 
Then, we could introduce this functionality on slayer.io as follows:
```
def read_2d_spikes_extended(filename):
    with open(filename, 'rb') as input_file:
        input_byte_array = input_file.read()
    input_as_int = np.asarray([x for x in input_byte_array])
    x_event = (input_as_int[0::12] << 8) + input_as_int[1::12]
    y_event = (input_as_int[2::12] << 8) + input_as_int[3::12]
    c_event = input_as_int[4::12] >> 7
    t_event = (
        (input_as_int[4::12] << 56)
        | (input_as_int[5::12] << 48)
        | (input_as_int[6::12] << 40)
        | (input_as_int[7::12] << 32)
        | (input_as_int[8::12] << 24)
        | (input_as_int[9::12] << 16)
        | (input_as_int[10::12] << 8)
        | (input_as_int[11::12])
    ) & 0x7FFFFFFFFFFFFFFF

    # convert spike times to ms
    return slayer.io.Event(x_event, y_event, c_event, t_event / 1000)
```
### Conditions of satisfaction
- Users can utilize io library to open more generic event datasets.

**Comment by bamsumit** [comment]
Hi @alexggener the 2d spikes format is specific to N-MNIST, N-Caltech101 dataset. For compatibility reasons, we would want to keep supporting the format as it is for historical reasons. For newer dataset, I recommend saving and reading the data in numpy format which is more general and supports your use case.
* [slayer.io.encode_np_spikes](https://lava-nc.org/lava-lib-dl/slayer/io.html#lava.lib.dl.slayer.io.encode_np_spikes)
* [slayer.io.read_np_spikes](https://lava-nc.org/lava-lib-dl/slayer/io.html#lava.lib.dl.slayer.io.read_np_spikes)
