### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava-dl#165]
### Discussed in https://github.com/lava-nc/lava-dl/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **Dola47** February 14, 2023</sup>
Hi All,

I am trying to install lava on Linux:

1- I go to my directory.

2- Then I run this command:

``git clone git@github.com:lava-nc/lava-dl.git``

3- After a while I am getting this error:

```
Cloning into 'lava-dl'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you help me with this error, given that I am able to clone other repos normally without any problem?

On the other way around when I clone the repo by doing:

``
git clone https://github.com/lava-nc/lava-dl.git
``

The repo is cloned normally. 

However, when I come to the step where I should run (I am done so, after activating a newly installed python environment): 
``
curl -sSL https://install.python-poetry.org | python3 -
``
I get this error:
``
curl: (6) Could not resolve host: install.python-poetry.org
``

Any idea how can I bypass either of the errors.

Thanks.</div>

**Comment by bamsumit** [comment]
Continuing from https://github.com/lava-nc/lava-dl/discussions/164#discussioncomment-4976109

Are you trying to install it in your home environment or work/university?

**Comment by Dola47** [comment]
@bamsumit Yes, it is a notebook for work.

**Comment by Dola47** [comment]
@bamsumit I think IT is not needed, I got it running on Linux, with this workaround.

```
1- git clone https://github.com/lava-nc/lava-dl.git
2- python -m venv .venv
3- source .venv/bin/activate.csh
4- pip install poetry
5- pip install --upgrade pip
6- pip install --upgrade pytest 
7- deactivate
8- source .venv/bin/activate.csh (again)
9- poetry config virtualenvs.in-project true
10- poetry install

Step 9, and 10 may need to be run several times, if some of the packages failed during running "poetry install"
