### ISSUE TITLE
Code Hangs Indefinitely When Evaluating Neuron Models on GPU

### ISSUE THREAD

**Issue by cscharzenberger** [lava-nc/lava-dl#182]
To Whom It May Concern:

**Describe the bug**
I have been encountering an issue in which my code hangs indefinitely when trying to evaluate neuron models on the GPU using Lava-DL.  If I switch to running it on the CPU, the code executes normally without hanging on the neuron model evaluation.  Interestingly, it has no difficulty executing the synapse models regardless as to whether I select the CPU or GPU, and torch is able to find and run on the GPU without a problem (e.g., torch.cuda.is_available() returns true).  I freshly installed pytorch, lava, and lava-dl from source by following the instructions on their respective github pages. 

**To reproduce current behavior**
1. When I run this code...
```python
# Import libraries.
import torch
import lava.lib.dl.slayer as slayer

# Set the device.
device = torch.device( 'cuda' ) if torch.cuda.is_available(  ) else torch.device( 'cpu' )           # This causes it to get stuck when evaluating neurons.
# device = 'cpu'                                                                                      # This works!

# Define the synapse and neuron parameters.
synapse_parameters = { 'gain' : 10.0 }
neuron_parameters = { 'threshold' : 1.0, 'current_decay' : 1.0, 'voltage_decay' : 1.0, 'persistent_state': False, 'requires_grad' : False }

# Create some synapses and neurons.
synapses = slayer.synapse.Dense( 1, 20, weight_scale = synapse_parameters[ "gain" ] ).to( device )
neurons = slayer.neuron.cuba.Neuron( threshold = neuron_parameters[ "threshold" ], current_decay = neuron_parameters[ "current_decay" ], voltage_decay = neuron_parameters[ "voltage_decay" ], persistent_state = neuron_parameters[ "persistent_state" ], requires_grad = neuron_parameters[ "requires_grad" ] ).to( device )

# Create a dummy network input tensor (these values do not matter, they are just to test the evaluation).
network_input = torch.unsqueeze( torch.tensor( [ [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ] ], dtype = torch.float32, device = device ), 1 )

# Print some general information.
print( '\nCuda Available: ', torch.cuda.is_available(  ) )
print( 'Device: ', device )

# Compute the synapse output.
print('\nEvaluating synapses...')
synapse_output = synapses( network_input )
print('Evaluating synapses... Done.')

# Compute the neuron output.
print('\nEvaluating neurons...')
neuron_output = neurons( synapse_output )
print('Evaluating neurons... Done.\n')
```
2. I get this result...
```
Cuda Available:  True
Device:  cuda

Evaluating synapses...
Evaluating synapses... Done.

Evaluating neurons...
```
... which isn't an error message, but rather shows that the code is getting stuck on the neuron model evaluation.

**Expected behavior**
I expect the code to give me the following result:
```
Cuda Available:  True
Device:  cuda

Evaluating synapses...
Evaluating synapses... Done.

Evaluating neurons...
Evaluating neurons... Done.
```
i.e., I expect the code to produce a neuron_output value and run to completion.  This is in fact what happens when I run the code on the CPU.

**Environment:**
 - Device: Laptop
 - OS: Linux
 - Python Version: 3.10.10
 - CUDA Version: 11.7
 - Torch Version: 1.13.1+cu117
 - Lava Version: 0.6.0
 - Lava-DL Version: 0.3.2

I am new to using lava and lava-dl, so I apologize if there is something simple that I am missing here.  Any insight into this issue would be greatly appreciated.

Thanks,

Cody Scharzenberger

**Comment by bamsumit** [comment]
Hi @cscharzenberger, thanks for reaching out. Can you check if you are facing same the issue described in https://github.com/lava-nc/lava-dl/issues/55#issuecomment-1076514132 ?

**Comment by pbonazzi** [comment]
I have encountered the same issue on : 

Environment:

Device: Laptop
OS: Linux
Python Version: 3.9
CUDA Version: 11.7
Torch Version: 1.13.1+cu117
Lava-DL Version: 0.3.3

**Comment by JuliaA369** [comment]
Thank you @bamsumit! I was experiencing this issue as well. I tried deleting the lock file in ~/.cache/torch_extensions/**** as suggested 
[here](https://github.com/zhou13/neurvps/issues/1#issuecomment-820898095)
and I am now able to run lava-dl on GPU!

**Comment by bamsumit** [comment]
Closing this issue; There is a relevant discussion thread for it: https://github.com/lava-nc/lava-dl/discussions/211
