### ISSUE TITLE
pytest not running

### ISSUE THREAD

**Issue by franzhd** [lava-nc/lava-dl#189]
**Describe the bug**
Pytest do not complete the execution, remain "collecting 0 items" forever.

**To reproduce current behavior**
1. installed lava-dl following the guidelines

**Expected behavior**
run correctly the tests 

**Screenshots**
![image](https://user-images.githubusercontent.com/58605124/235698108-79100186-d099-4f81-ab53-4360bd45224d.png)

**Environment (please complete the following information):**
 - Device: Desktop r5 3600 and rtx3070 cuda 11.7 
 - OS: Ubuntu Linux 22.04
 - Lava version : Lava-nc 0.7.0 lava-dl 0.3.3

**Additional context**
Add any other context about the problem here. Remove section otherwise.

**Comment by bamsumit** [comment]
@franzhd it has been working consistently for our other use cases. Alternatively, you can test your installation using `python -m unittest`. I suspect it has to do with custom cuda compilation on your system. Perhaps this is useful: https://github.com/lava-nc/lava-dl/issues/55#issuecomment-1076514132

**Comment by bamsumit** [comment]
@franzhd if you got it working, can we close this issue?

**Comment by franzhd** [comment]
sorry for the delay, i had no possibility to go back working on this. 
I found that the suggested command works but it is not verbose enough, can you help me understand if everything is went well?
![image](https://github.com/lava-nc/lava-dl/assets/58605124/41696fa4-bbb5-4c8d-a8d8-a9331b30d8da)
Thanks again for your help :D

**Comment by bamsumit** [comment]
@franzhd yes it is working. I am closing this issue then.
