### ISSUE TITLE
How to approximate the non-linear activation function in ANN using lava.dl to extend its application?

### ISSUE THREAD

**Issue by zjuls** [lava-nc/lava-dl#195]
### User story
As a user, I want to learn how to approximate the non-linear activation function in ANN using lava.dl to extend its application.

### Conditions of satisfaction
- An optional list of conditions that have to be fulfilled for this feature to be complete.
- Users can choose either a sparse or normal system to adapt different applications

**Comment by bamsumit** [comment]
@zjuls can you explain more about the feature you are asking for? Have you looked at `lava.dl.bootstrap`?

**Comment by zjuls** [comment]
Thanks for your time! I mean is there a way to use torch.nn.relu or other non-linear activation function in lava.dl? Or is there a chance to train a model  using torch/tensorflow and implement it with lava on loihi?
