### ISSUE TITLE
ipython package not included in requirements.txt

### ISSUE THREAD

**Issue by alexggener** [lava-nc/lava-dl#21]
When creating and installing a venv for LAVA from scratch, pip does not include ipython package. This package is needed for the Spike to Spike Regression: Oxford in lava-dl. Should this package be included in the requirements.txt for lava-dl?

Cheers,
Alex.

**Comment by bamsumit** [comment]
@alexggener, thanks for letting us know. Hope that didn't block you from running the tutorials. You may create a pull request with `jupyterlab` in `requirements.txt`.
