### ISSUE TITLE
Some questions about converting lava-dl into lava.

### ISSUE THREAD

**Issue by wangtianrui** [lava-nc/lava-dl#210]
I encountered problems when I converted a model trained with lava-dl and pytorch into lava.

1. ConvT
   I trained a model containing the 'ConvT' module. But I met the problem 'NotImplementedError: convT is not implemented' when I load the model on lava with the function 'netx.hdf5.Network'. 
  https://github.com/lava-nc/lava-dl/blob/add48805c3fe7e873d7fae5705b0711b9652332b/src/lava/lib/dl/netx/hdf5.py#L575
  Is there an implementation for the conversion of 'ConvT' (lava-dl to lava)?

2. I trained a model with lava-dl and pytorch. The model contain some operations like 'x = x[:, :-1]' and 'x = torch.cat([x1, x2], dim=1)'. When I convert the lava-dl model into lava, I notice that the operations are removed. How can I refine the process of the converted model from lava-dl to lava?

I am looking forward to your reply. Thank you.

**Comment by bamsumit** [comment]
@wangtianrui ConvT is not fully supported by underlying Lava for inference. Therefore, the export in Lava-DL is currently not implemented. This conversation can be of interest for you: https://github.com/lava-nc/lava-dl/issues/74
