### ISSUE TITLE
[PilotNet Tutorial]: Google Drive URL dataset is not valid

### ISSUE THREAD

**Issue by Barchid** [lava-nc/lava-dl#22]
Hello,

I tried to run the tutorial about car steering prediction using a sigma-delta neural network. Unfortunately, the Google Drive URL referenced in `lava-dl/tutorials/lava/lib/dl/slayer/pilotnet/pilotnet_dataset.py` is not working anymore. For information, the referenced URL is the following: https://drive.google.com/file/d/0B-KJCaaF7elleG1RbzVPZWV4Tlk/view?usp=sharing . 

I also checked the URL from the original PilotNet repository ( https://github.com/lhzlhz/PilotNet ) and the URL does not work as well, since it is the same.

Can you provide a new link if possible ?

Thanks for your help and for your awesome project!

**Comment by bamsumit** [comment]
Hi @Barchid, thanks for letting us know. The link indeed does not work now. I have filed an issue in the original repo [here](https://github.com/AutoDeep/PilotNet/issues/1). We will have to wait until the link gets fixed

**Comment by s7117** [comment]
I am not sure if the datasets are the exact same, but I followed the forks of the repo and found some datasets [here](https://github.com/SullyChen/driving-datasets). The data format seems to be similar with the filename (*.jpg) and the steering wheel angle.

Fork trace:
[AutoDeep/PilotNet](https://github.com/AutoDeep/PilotNet) forked from [s7ev3n/Nvidia_Autopilot_with_DriveActivation](https://github.com/s7ev3n/Nvidia_Autopilot_with_DriveActivation) which is forked from [SullyChen/Autopilot-TensorFlow](https://github.com/SullyChen/Autopilot-TensorFlow) which leads to https://github.com/SullyChen/driving-datasets when you click on data.

**Comment by bamsumit** [comment]
@s7117 Thanks a lot for digging it out. It looks like they are same. I'll do some more checks and update the link.
