### ISSUE TITLE
Pytorch 2+

### ISSUE THREAD

**Issue by ahenkes1** [lava-nc/lava-dl#220]
### User story
As a user, I want to use Pytorch 2+ to use the latest features. This would ease adding new features to lava-dl. I tried the latest 2.0.1 version and everything works just fine. Currently, a legacy version is required by lava-dl.

### Conditions of satisfaction
The requirements should be updated to pull the latest Pytorch version. All tests pass on the latest 2.0.1 version.

**Comment by tim-shea** [comment]
After a brief discussion with @bamsumit, it sounds like Lava-DL is actually fully compatible with torch 2+. We can do a bit more testing and try to update the project dependencies before the next release, but in the mean time @ahenkes1 please consider editing your pyproject.toml (assuming you use `pip install`) and please report any issues you encounter.

**Comment by ahenkes1** [comment]
Sure! I have been running lava-dl with Pytorch 2 for some time now and haven't had any issues so far.
