### ISSUE TITLE
Deactivate utils.LearningStats "accuracy" display during utils.Assistant.train() using flag 

### ISSUE THREAD

**Issue by ahenkes1** [lava-nc/lava-dl#223]
### User story
As far as I am informed, it is not possible to deactivate the "accuracy" value display during the convenient utils.Assistant.train() run. For regression tasks, this is redundant. The print message is controlled via utils.LearningStats and could be deactivated via a Flag. I have not found a possibility to deactivate the "accuracy" message in the current version. If there is no way to do this by a way I am not aware of, I would be happy to implement this feature.

### Conditions of satisfaction
- Implement a flag "display_accuracy=True". The default value would be "True", as most people using lava-dl are interested in classification, I guess.
- The simplest way to do this is to simply modify the print message. However, one could also deactivate the computation of the accuracy completely. I am open for preferences from your side.

### Acceptance tests
- A test comparing the output string could be added for both "True" and "False" values.

In case this feature is "missing" you can simply assign me to this Issue.

**Comment by bamsumit** [comment]
@ahenkes1  You can change the string to something else that is relevant for what you are doing. You can do that when instantiating the stats like this
```python
stats = slayer.utils.LearningStats(accuracy_str='SI-SNR', accuracy_unit='dB')
```

**Comment by ahenkes1** [comment]
@bamsumit , thank you for the feedback. Deactivating is currently not supported?

**Comment by bamsumit** [comment]
If you do not load accuracy entries, it will not print it out.
![image](https://github.com/lava-nc/lava-dl/assets/29907126/ce003ced-a46a-407f-bce3-bc2abea92422)
