### ISSUE TITLE
Netx should not set max delay when creating Dense block

### ISSUE THREAD

**Issue by tim-shea** [lava-nc/lava-dl#226]
**Describe the bug**
Netx clips delays greater than 63 to be compatible with Loihi 2, but also sets max delay equal to 62 regardless of the actual max delay, which then leads to a size mismatch when adding synapse delay matrix to a_buff.

**To reproduce current behavior**
Run NDNS lava inference with the latest commit.

**Expected behavior**
Dense block constructor should either pass max_delay of 0 to let the block infer the correct value from the delay matrix or else Delay process should be updated so that the shape of a_buff is computed from the actual delay matrix instead of max delay.

**Environment:**
 - Device: laptop
 - OS: Mac os
 - Lava version v0.8

**Comment by bamsumit** [comment]
@tim-shea are you sure you are using the latest lava main? There is a PR that handles this inconsistent buffer shape issue: https://github.com/lava-nc/lava/pull/767
