### ISSUE TITLE
Support verification and optimization of YoloKP on Loihi2

### ISSUE THREAD

**Issue by joyeshmishra** [lava-nc/lava-dl#252]

**Comment by Gavinator98** [comment]
I've been trying to run the YoloKP on chip for a couple days using the #243 PR branch. A couple things I've encountered so far:
- The [tutorials/lava/lib/dl/slayer/tiny_yolo_sdnn/Trained_yolo_kp/network.net](https://github.com/lava-nc/lava-dl/pull/243/files#diff-74334005d1ca37a75ef7bea31f6b8255bb5a45d600301d1ccdaf382305b840d2) file has two issues in the head layer: it is missing the `neruon` field and the `weights` are missing the spatial dimensions. 
- After fixing those issues the model compiles on my machine but the INRC cloud vm runs out of RAM.

**Comment by bamsumit** [comment]
First point has been fixed in the merged code base. For second point, please contact inrc_support.
