### ISSUE TITLE
Multi-GPU Training 

### ISSUE THREAD

**Issue by michaelneumeier** [lava-nc/lava-dl#26]
Is training on multiple GPUs possible with the current lava-dl release?

I distribute the batch for the nmnist tutorial on two GPUs with:
_net = Network()
net = nn.DataParallel(net, device_ids=[0, 1])
net.to(device)_

The training for the first epoch runs as expected. In the second epoch I get an error during backpropagation:
_Traceback (most recent call last):
  File "nmnist.py", line 220, in <module>
    output, count = assistant.train(input, label)
  File "/home/user/lava-dl/src/lava/lib/dl/slayer/utils/assistant.py", line 139, in train
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: output with shape [1] doesn't match the broadcast shape [512]_ 

Is this a known issue and can you reproduce it on your GPU clusters? Or is it specific to my GPU settings? Or is there extra code necessary to enable multiple GPU training?

Thank you for your support.

**Comment by bamsumit** [comment]
Hi @michaelneumeier can you try this.
```python
net = Network()
net.forward(torch.rand(1, C, H, W, 1).to(device))  # CHW = your input dimension
net = nn.DataParallel(net, device_ids=[0, 1])
net.to(device)
```

**Comment by michaelneumeier** [comment]
Thank you @bamsumit for the quick reply.

I cannot run the exact code that you proposed. For this I get a device mismatch between the input tensor and weight tensor. Thus I tried this:
```python
net = Network().to(device)
net.forward(torch.rand(1, 2, 128, 128, 1).to(device))
net = nn.DataParallel(net, device_ids=[0, 1])
```
Then this code snippet works. 

If I run it before the training loop, I can even run the training for several epochs without receiving the backprop error message from the previous comment. 
But without the net.forward line, the error is still there. Do you understand why this is the case?

So thank you for the hint, I can now train on multiple GPUs.

**Comment by bamsumit** [comment]
Glad you can run it now. The slayer models support _runtime shape identification_. This means that we don't need to specify the shape of a layer. Instead they are identified on runtime. With multi GPU, the shape update happens on the spawned dataparallel copy but is not reflected back on the main model, so it needs to be done __on the main copy once with a dummy load__ before the multiGPU run. This should also work.
```python
net = Network().to(device)
net = nn.DataParallel(net, device_ids=[0, 1])
...
net.module.forward(torch.rand(1, 2, 128, 128, 1).to(device))
# training sequence
```
