### ISSUE TITLE
Allow slayer norms to use parameters 

### ISSUE THREAD

**Issue by Gavinator98** [lava-nc/lava-dl#301]
### User story
As a user, I want to modify the arguments to slayer neuron norms. 
The neuron norms provide arguments to adjust momentum and other parameters:
https://github.com/lava-nc/lava-dl/blob/543efaac136bfb028f1445f0384fe36555c0fc21/src/lava/lib/dl/slayer/neuron/norm.py#L36

However, when used the neuron calls the constructor with no arguments:
https://github.com/lava-nc/lava-dl/blob/543efaac136bfb028f1445f0384fe36555c0fc21/src/lava/lib/dl/slayer/neuron/base.py#L146

As a workaround it might be possible to use a lambda function as the norm argument:
```python
params = {
    "norm": lambda x: slayer.neuron.norm.MeanOnlyBatchNorm(momentum=0.2)
}
```

**Comment by PhilippPlank** [comment]
Thank you for this suggestion. @bamsumit Could you take a look, when you find some time :)

**Comment by bamsumit** [comment]
@Gavinator98 The intended usage pattern is to call a lambda like you mention. This is by design because the norm could have other signatures and therefore cannot be known in advance.
