### ISSUE TITLE
Making the decay parameters(dv,du) learnable and separate du, dv for different layers?

### ISSUE THREAD

**Issue by naveedunjum** [lava-nc/lava-dl#303]
Is there a way to make the decay parameters learnable? I want to train a network that can also adjust the decay parameters for the individual neurons.

Also is it possible to use different du, dv settings for different layers?

**Comment by bamsumit** [comment]
@naveedunjum Yes and Yes.
1. To make the decay parameters learnable, you can set `requires_grad = True` in the neuron parameter.
2. You can use different neuron parameters for different layers and thus have different `u_decay` and `v_decay`.
