### ISSUE TITLE
build fails when installing lava-dl on top of lava 2.0 binaries

### ISSUE THREAD

**Issue by biphasic** [lava-nc/lava-dl#32]
That's the output I get: https://pastebin.com/0V4WtZPq
I'm on Ubuntu 20.04, conda 4.10.3 and Python 3.9.7.

**Comment by bamsumit** [comment]
Hi @biphasic, can you try `python -m unittest` and see of that works?

**Comment by biphasic** [comment]
Hello, I got it working in the end when I managed to build lava from source on another machine. Closing this for now.
