### ISSUE TITLE
[BUG] Salyer - Application of normalization function in CUBA neuron  

### ISSUE THREAD

**Issue by lukaszpindor** [lava-nc/lava-dl#33]
Objective of issue:
Normalization function in CUBA neuron is applied on "input" variable which has no effect on code.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**
![image](https://user-images.githubusercontent.com/91951071/152143161-b6b2229b-4f41-415a-a941-8c6f2c356f96.png)
Normalization function in CUBA neuron is applied on "input" variable which has no effect on code.

**Expected behavior:**
If this normalization function needs to be applied on "input" it should be implemented before calculation of current dynamics. 
If this normalization function should be applied on "current", then the variable name should be changed.

**Comment by mgkwill** [comment]
Hi @lukaszpindor. Thanks for reporting this!

@bamsumit any thoughts?

**Comment by bamsumit** [comment]
It looks like a bug. Thanks @lukaszpindor. I'll issue a fix.
