### ISSUE TITLE
Correction for installation from binaries. 

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#39]
Hello,
It seems the installation procedure given for installing from binaries is copy-pasted from the main lava repository and may lead others to reinstall main lava instead of installing lava-dl.
A possible correction might be `pip install lava-dl-0.1.1.tar.gz `
Sincerely,

PS. I am having problems with pybuilder in every lava repository in every os constantly. This might be stemmed from both they are new repos under construction and I am not an expert on those builders (I have not experienced so much different errors in any other mainstream framework though). So, it might be nice to test those procedures on an empty computer to see what might be wrong.

**Comment by mgkwill** [comment]
> Hello, It seems the installation procedure given for installing from binaries is copy-pasted from the main lava repository and may lead others to reinstall main lava instead of installing lava-dl. A possible correction might be `pip install lava-dl-0.1.1.tar.gz ` Sincerely,
> 
> PS. I am having problems with pybuilder in every lava repository in every os constantly. This might be stemmed from both they are new repos under construction and I am not an expert on those builders (I have not experienced so much different errors in any other mainstream framework though). So, it might be nice to test those procedures on an empty computer to see what might be wrong.

Hi @ahmetakman. Thanks for pointing this out. The installation instruction should be updated. 

As far as the pybuilder issue, I'm aware of it. I'm in the process of migrating away from pybuilder for build, linting, unit test runs for the release we are working on right now.  When this migration is finished the docs will be updated to match. Stay tuned.

**Comment by bamsumit** [comment]
@ahmetakman is this issue resolved?
