### ISSUE TITLE
About some problems occurred in the NMNIST training example in Windows

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#50]
Hello,
Currently, I am running/trying to run NMNIST training example on my both computers one of them is Windows and uses CUDA, and the other one is an Ubuntu computer with no CUDA support. 
I am running the notebook successfully on my Ubuntu computer without a problem but since it is only CPU (an old one) it is quite slow as expected.

For windows, there are some problems, and probably just because of the windows system's unique requirements. Let me express them.
Firstly the windows indexing convention makes some of the codes no longer useful. I have solved the problem in the nmnist.py by replacing the split('/') with '\\' however this is not a proper solution. There might be better ways to solve this incompatibility.

On the other hand, I have got an error about Visual Studio environment variables, ' [CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.]() '  I will try to solve this issue also by myself since it is probably because windows C++ environment setup.

P.S.: I am aware it is best to switch the  OS of the better computer to Ubuntu, but right now  it is not a possible option ( I really do not like to work with windows, I will switch soon.)

All the best,

**Comment by bamsumit** [comment]
Hi @ahmetakman, thanks for pointing out the windows path issue on `tutorials/lava/lib/dl/slayer/nmnist/nmnist.py`. We will issue a fix on that soon.

On the error, can you post the detailed error output?

Also can you post the output of the following commands?
```cmd
nvcc --version
nvidia-smi
```

**Comment by ahmetakman** [comment]
Well , I have switched my OS to Ubuntu ,but my CUDA version was 10.2 and my graphic card is GTX 1650 (I do not remember the driver version but it was probably 470) . I can not reproduce the error right now but I have not faced this particular issue in Ubuntu.
