### ISSUE TITLE
NetX Dimension Seems Lost

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#53]
Hello,
I have trained  the 3 fully connected layer network using NMNIST dataset ( using the tutotorial notebook ) 

When I try to convert this model to the process network I have got the dimension different. 
 The network blocks in Slayer was;
self.blocks = torch.nn.ModuleList([
                slayer.block.cuba.Dense(neuron_params_drop, 34*34*2, 512, weight_norm=True, delay=True),
                slayer.block.cuba.Dense(neuron_params_drop, 512, 512, weight_norm=True, delay=True),
                slayer.block.cuba.Dense(neuron_params, 512, 10, weight_norm=True),
            ])

However when I convert it using NetX it becomes:

There are 3 layers in network:
Dense : Process_1 , shape : (512,)
Dense : Process_4 , shape : (512,)
Dense : Process_7 , shape : (10,)

There might be something wrong with what I am doing but I could not figure it out. 
Simply  I have used 
net = netx.hdf5.Network(net_config='Trained/network.net')
print(net)

Just like what has been done in the NetX tutorials.

All the best,
Ahmet Akman

Objective of issue:

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [ ] documentation request
- [x] I really do not know right now it might be a bug , might be a documentation request.

**Comment by bamsumit** [comment]
@ahmetakman your network, as you defined in `self.blocks`, has two hidden layers and one output layer of dimensions 512, 512, and 10 respectively. So it does make sense to get the dimension of the network as 512, 512, and 10 when you load the network, isn't it?

**Comment by ahmetakman** [comment]
I though the dimension should be 
Dense : Process_1 , shape : (34*34*2,512)
Dense : Process_4 , shape : (512,512)
Dense : Process_7 , shape : (512,10)
As were in the NetX examples.

**Comment by bamsumit** [comment]
Look at the dense block definition in [PilotNet SDNN training](https://github.com/lava-nc/lava-dl/blob/main/tutorials/lava/lib/dl/slayer/pilotnet/train.ipynb)
![image](https://user-images.githubusercontent.com/29907126/158875721-ed81419e-ce13-4e5d-94f3-2436aaf145aa.png)
and the shapes in [PilotNet SDNN inference](https://github.com/lava-nc/lava-dl/blob/main/tutorials/lava/lib/dl/netx/pilotnet_sdnn/run.ipynb) with NetX
![image](https://user-images.githubusercontent.com/29907126/158875553-aed773ad-eefa-4dfa-b47e-920f768d5bd9.png)

**Comment by ahmetakman** [comment]
I have mistaken the error about the dimensions I got when was connecting the processes. I will try again soon ,and write back. Thanks for the reply.

**Comment by ahmetakman** [comment]
Let me come back to here,

First of all, I am not sure my environment is fully utilized but at some point I have a system with barely passing unit tests with hanging code block issue #55 . 

Here my interpretation about NetX dimensions is still because of the current error I am getting. Let me summarize my goal then give the error.

 I would like to run trained NMNIST model with lava core by using NetX network exchange. The result of the conversion is given above. 

When I try to connect processes with the code block:
`gt_logger = io.sink.RingBuffer(shape=(1,), buffer=num_steps)
output_logger = io.sink.RingBuffer(shape=net.out_layer.shape, buffer=num_steps)
dataloader.ground_truth.connect(gt_logger.a_in)
dataloader.s_out.connect(net.in_layer.neuron.a_in) ***** issue line ********
net.out_layer.out.connect(output_logger.a_in)`

I get the error 

AssertionError: Shapes torch.Size([2312]) and (512,) are incompatible.]()

First, my interpretation was the dimension was lost since it is 512 not 2312

**Comment by bamsumit** [comment]
Aren't you supposed to connect the `dataloader.s_out` to `net.in_layer.synapse.s_in` ? It seems you are bypassing the syanpse of the first layer!

```python
dataloader.s_out.connect(net.in_layer.syanpse.s_in)
```

**Comment by ahmetakman** [comment]
Yeah that was it, now I have connected processes the run config is running right now.

Thank you very much for the explanation. I sincerely thank for your patience. 

I am actively learning the lava-ecosystem, SNNs ,and the new computers I am running them on. 
Until I completely got the structure, I think it is natural to misunderstand some concepts.

I am closing the issue, 
All the best,
Ahmet.

**Comment by bamsumit** [comment]
No problem @ahmetakman, happy to clarify any confusion.
