### ISSUE TITLE
The Input dimensions of the CUBA and other blocks

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#54]
Hello,
I am simply trying to train a simple network to re-train a simple network of which has layers 

        self.blocks = torch.nn.ModuleList([
                slayer.block.cuba.Input(neuron_params),
                slayer.block.cuba.Dense(neuron_params_drop, 34*34*2, 512, weight_norm=True, delay=True),
                slayer.block.cuba.Dense(neuron_params_drop, 512, 512, weight_norm=True, delay=True),
                slayer.block.cuba.Dense(neuron_params, 512, 10, weight_norm=True),
            ])

But, I am unable to figure out how the input layer should be shaped. I could not find any explanation in the type declaration codes unfortunately. This documentation request is not only for Input block but also when I try to add a convolutional layer (it seems library does not follow PyTorch convention straight forward) I can not figure it out the how the Conv block dimensions are formed. So I am getting dimensions more than I expected.  

Can you explain the input parameter requirements of the block little bit?

My attempt of re-training is related to the issue #53 . 

All the best,

Operation system Ubuntu 20.04

Objective of issue:

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [x] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by bamsumit** [comment]
Hi @ahmetakman, SLAYER neurons can determine their shape during runtime based on the input they get for the first time. So what you have got above is technically correct.

Since the next dense layer expects `34*32*2` input neurons in your code, your input block should also be initialized to the same dimension. This in turn means that the input data you feed into the network should also be the same dimension.

**Comment by ahmetakman** [comment]
Thanks for the explanation If i can solve the issue #55  I will come back and try again.
