### ISSUE TITLE
Hanging code block issue

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#55]
Hello,

I have been re-attempting to train  another network on NMNIST dataset ,but I am getting the issue #54 . 
In addition, currenty when I try to run the NMNIST training code directly from tutorial ( It was working properly yesterday ) the code is hanging in the training notebook block inconsistenly. Setup is same, tutorial is same , variables are same but the code is hanging this is another problem I am facing.

When I interrupt the kernel it does not stop and needs restart.

![Screenshot from 2022-03-14 12-35-29](https://user-images.githubusercontent.com/24481964/158145127-dab49d56-b944-4def-bcd2-b3d617395e1a.png)

Setup is GTX1650 GPU and Ubuntu 20.04 and I am getting no epoch in 20 mins. Which is weird because I was getting one epoch per 8 mins.

All the best,
Ahmet

Objective of issue:

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by ahmetakman** [comment]
UPDATE : I find out that , the code is working with CPU but not working GPU even though CUDA initializes and `torch.cuda.isavailable()` turns "True" .  I am looking for solutions in the PyTorch forum if I can solve I will update here.

**Comment by bamsumit** [comment]
Hi @ahmetakman, can you also try and run these commands in python interpreter and see if it executes? https://github.com/lava-nc/lava-dl/issues/40#issuecomment-1069669742

Since you say it was running the day before, have you tried restarting your system?

**Comment by ahmetakman** [comment]
Yeah it executes successfully without any error
![Screenshot from 2022-03-17 20-15-40](https://user-images.githubusercontent.com/24481964/158857045-9f0d1b83-3555-4e2b-bb28-90bdafcace2f.png)
.

**Comment by bamsumit** [comment]
Did you try restarting your system?

**Comment by bamsumit** [comment]
Are you able to run unittests on Lava-DL successfully?

**Comment by ahmetakman** [comment]
Yes I am. I have ran the unittests successfully couple of times and I will try again to verify .

**Comment by ahmetakman** [comment]
UPDATE : The unittests are no longer passing right now (seems because of a cuda issue). 
The current setup;
GPU: GTX1650
Nvidia Driver : v510
CUDA version 10.1
torch version 1.8.1+cu101 (simple torch cuda operations are working correctly)

The problem I have mentioned in #52  is exactly like that but even if recover the unittests with different cuda setup (which was cuda version 11.3 and driver version v510 [or v470 , tried both] ) I am facing problems in this very issue. 

The output of the unittests is;

FAIL Required test coverage of 45.0% not reached. Total coverage: 33.38%
======================================================================================== short test summary info =========================================================================================
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf.py - RuntimeError: Error building extension 'dynamics': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output resonator.cuda.o.d ...
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf_iz.py - RuntimeError: Error building extension 'dynamics_v1': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output adaptive_reso...
ERROR tests/lava/lib/dl/slayer/neuron/test_alif.py - RuntimeError: Error building extension 'dynamics_v2': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output leaky_integrator...
ERROR tests/lava/lib/dl/slayer/neuron/test_cuba.py
ERROR tests/lava/lib/dl/slayer/neuron/test_rf.py - RuntimeError: Error building extension 'dynamics_v3': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output resonator.cuda.o.d...
ERROR tests/lava/lib/dl/slayer/neuron/test_rf_iz.py
ERROR tests/lava/lib/dl/slayer/neuron/test_sigma_delta.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_phase_th.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_resonator.py - RuntimeError: Error building extension 'dynamics_v4': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py - RuntimeError: Error building extension 'dynamics_v5': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py - RuntimeError: Error building extension 'dynamics_v6': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output re...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 3 warnings, 12 errors in 8.36s ======================================================================================


All the best.

**Comment by ahmetakman** [comment]
I have a question. Would the lava-dl work in the setup of newer torch versions than 1.8.1 ?

**Comment by bamsumit** [comment]
Yes. I have it running on multiple different cuda and torch versions. The most newest config that works for me is __torch 1.11.0__ with __cuda 11.3__

**Comment by ahmetakman** [comment]
So the the installation done by poetry is outdated ?

**Comment by bamsumit** [comment]
No, everything still works with __torch 1.8.1__. That is the recommended version. Everything was fully tested and developed with that version of torch. 

I am just confirming that we have it working with newer torch version if you have problems installing torch 1.8.1

**Comment by VishalPathak-GTRI** [comment]
What CUDA version would you say is best to run all test code?

**Comment by bamsumit** [comment]
@VishalPathak-GTRI the latest cuda version is always good if you can install it.

**Comment by bamsumit** [comment]
> UPDATE : The unittests are no longer passing right now (seems because of a cuda issue). The current setup; GPU: GTX1650 Nvidia Driver : v510 CUDA version 10.1 torch version 1.8.1+cu101 (simple torch cuda operations are working correctly)
> 
> The problem I have mentioned in #52 is exactly like that but even if recover the unittests with different cuda setup (which was cuda version 11.3 and driver version v510 [or v470 , tried both] ) I am facing problems in this very issue.
> 
> The output of the unittests is;
> 
> FAIL Required test coverage of 45.0% not reached. Total coverage: 33.38% ======================================================================================== short test summary info ========================================================================================= ERROR tests/lava/lib/dl/slayer/neuron/test_adrf.py - RuntimeError: Error building extension 'dynamics': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output resonator.cuda.o.d ... ERROR tests/lava/lib/dl/slayer/neuron/test_adrf_iz.py - RuntimeError: Error building extension 'dynamics_v1': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output adaptive_reso... ERROR tests/lava/lib/dl/slayer/neuron/test_alif.py - RuntimeError: Error building extension 'dynamics_v2': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output leaky_integrator... ERROR tests/lava/lib/dl/slayer/neuron/test_cuba.py ERROR tests/lava/lib/dl/slayer/neuron/test_rf.py - RuntimeError: Error building extension 'dynamics_v3': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output resonator.cuda.o.d... ERROR tests/lava/lib/dl/slayer/neuron/test_rf_iz.py ERROR tests/lava/lib/dl/slayer/neuron/test_sigma_delta.py ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_phase_th.py ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_resonator.py - RuntimeError: Error building extension 'dynamics_v4': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-... ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py - RuntimeError: Error building extension 'dynamics_v5': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-... ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py - RuntimeError: Error building extension 'dynamics_v6': [1/2] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output re... !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ===================================================================================== 3 warnings, 12 errors in 8.36s ======================================================================================
> 
> All the best.

@ahmetakman can you post the full debug output?

**Comment by ahmetakman** [comment]
UPDATE: I have updated my CUDA to 11.3 and installed latest torch version. Then I have ran the unittests. Unittests also hangs at `tests/lava/lib/dl/slayer/utils/filter/test_conv_filter.py `

When I interrupt the run  I am getting quite similar traceback with the code hanging issue.
 Here it is :
(.venv) ahmetakman@ahmetakman-ABRA-A5V15-2:~/lava-dl$ pytest
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/ahmetakman/lava-dl, configfile: pyproject.toml, testpaths: tests
plugins: cov-3.0.0
collected 86 items                                                                                                                                                                                        

tests/lava/lib/dl/netx/test_blocks.py ...                                                                                                                                                           [  3%]
tests/lava/lib/dl/netx/test_hdf5.py ...                                                                                                                                                             [  6%]
tests/lava/lib/dl/slayer/neuron/test_adrf.py .......                                                                                                                                                [ 15%]
tests/lava/lib/dl/slayer/neuron/test_adrf_iz.py .......                                                                                                                                             [ 23%]
tests/lava/lib/dl/slayer/neuron/test_alif.py .......                                                                                                                                                [ 31%]
tests/lava/lib/dl/slayer/neuron/test_cuba.py .......                                                                                                                                                [ 39%]
tests/lava/lib/dl/slayer/neuron/test_rf.py .......                                                                                                                                                  [ 47%]
tests/lava/lib/dl/slayer/neuron/test_rf_iz.py .......                                                                                                                                               [ 55%]
tests/lava/lib/dl/slayer/neuron/test_sigma_delta.py .....                                                                                                                                           [ 61%]
tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_phase_th.py ......                                                                                                                           [ 68%]
tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_resonator.py ......                                                                                                                          [ 75%]
tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py .....                                                                                                                           [ 81%]
tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py .....                                                                                                                             [ 87%]
tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py .....                                                                                                                                    [ 93%]
tests/lava/lib/dl/slayer/utils/filter/test_conv_filter.py ^C

============================================================================================ warnings summary =============================================================================================
tests/lava/lib/dl/netx/test_blocks.py:28
  /home/ahmetakman/lava-dl/tests/lava/lib/dl/netx/test_blocks.py:28: PytestCollectionWarning: cannot collect test class 'TestRunConfig' because it has a __init__ constructor (from: tests/lava/lib/dl/netx/test_blocks.py)
    class TestRunConfig(RunConfig):

tests/lava/lib/dl/netx/test_hdf5.py:26
  /home/ahmetakman/lava-dl/tests/lava/lib/dl/netx/test_hdf5.py:26: PytestCollectionWarning: cannot collect test class 'TestRunConfig' because it has a __init__ constructor (from: tests/lava/lib/dl/netx/test_hdf5.py)
    class TestRunConfig(RunConfig):

.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3
  /home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                                           Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------
src/lava/lib/dl/netx/__init__.py                                   3      0   100%
src/lava/lib/dl/netx/blocks/__init__.py                            0      0   100%
src/lava/lib/dl/netx/blocks/models.py                             31      2    94%   26, 31
src/lava/lib/dl/netx/blocks/process.py                            88      5    94%   49, 57, 89, 147, 209
src/lava/lib/dl/netx/hdf5.py                                     177     44    75%   65, 104-130, 199, 204, 241-274, 391-423
src/lava/lib/dl/netx/utils.py                                     73     36    51%   99-141, 162-172
src/lava/lib/dl/slayer/__init__.py                                12      0   100%
src/lava/lib/dl/slayer/auto.py                                   111     96    14%   28-31, 50-54, 88-98, 105-132, 137-141, 146-152, 157-208, 213-227, 233-242
src/lava/lib/dl/slayer/axon/__init__.py                            3      0   100%
src/lava/lib/dl/slayer/axon/delay.py                              71     41    42%   66-77, 82-86, 91-93, 109-142, 174-175, 184-198, 204-220
src/lava/lib/dl/slayer/axon/delta.py                              90     30    67%   29-40, 84-121, 254, 262, 268-270, 275, 296-297, 300, 316
src/lava/lib/dl/slayer/block/__init__.py                           2      0   100%
src/lava/lib/dl/slayer/block/adrf.py                              76     39    49%   18-23, 40-42, 50, 58, 68, 76-80, 88-92, 100-104, 112-116, 124-130
src/lava/lib/dl/slayer/block/adrf_iz.py                           76     39    49%   18-23, 40-42, 50, 58, 69, 77-81, 89-93, 101-105, 113-117, 125-131
src/lava/lib/dl/slayer/block/alif.py                              76     39    49%   18-23, 40-42, 50, 58, 68, 76-80, 88-92, 100-104, 112-116, 124-130
src/lava/lib/dl/slayer/block/base.py                             417    347    17%   37-74, 79-99, 105-108, 118-135, 149-152, 157-163, 173-176, 192-195, 201-207, 213, 223-226, 264-290, 295-314, 320, 330-358, 378-389, 394-412, 418, 428-431, 469-495, 500-517, 523, 533-583, 633-656, 661-671, 677, 687-743, 786-808, 813-823, 829, 839-878, 943-978, 981, 994-1034, 1040, 1050, 1093-1128, 1135-1162, 1168, 1178
src/lava/lib/dl/slayer/block/cuba.py                              85     45    47%   19-24, 41-43, 51, 59, 67-73, 81, 89-93, 101-105, 113-117, 125-129, 137-143
src/lava/lib/dl/slayer/block/rf.py                                85     45    47%   18-23, 39-41, 49, 57, 65-71, 79, 87-91, 99-103, 111-115, 123-127, 135-141
src/lava/lib/dl/slayer/block/rf_iz.py                             85     45    47%   18-23, 40-42, 50, 58, 66-72, 80, 88-92, 100-104, 112-116, 124-128, 136-142
src/lava/lib/dl/slayer/block/sigma_delta.py                      102     67    34%   18-28, 44-46, 52-65, 73, 81, 89-93, 101-105, 113-117, 167-176, 181-186, 192, 202-235
src/lava/lib/dl/slayer/classifier.py                              48     29    40%   39, 44, 68, 98-104, 128-129, 169-173, 193, 216-232, 252, 257
src/lava/lib/dl/slayer/dendrite/__init__.py                        2      0   100%
src/lava/lib/dl/slayer/dendrite/sigma.py                          22      2    91%   44, 51
src/lava/lib/dl/slayer/io.py                                     282    262     7%   45-87, 112-129, 161-242, 250-291, 299-351, 359-436, 461-477, 511-540, 567-599, 629-641, 666-685, 715-728, 755-775, 803-825, 849-868
src/lava/lib/dl/slayer/jitconfig.py                                8      1    88%   18
src/lava/lib/dl/slayer/loss.py                                    65     50    23%   38-45, 50, 97-113, 118-141, 177-183, 188-208
src/lava/lib/dl/slayer/neuron/__init__.py                          5      0   100%
src/lava/lib/dl/slayer/neuron/adrf.py                            208     83    60%   44-48, 169, 174, 179, 214-294, 383, 392, 402, 412, 417, 428, 466, 473-516, 519, 524, 549-558, 566, 569, 571, 655, 676-677
src/lava/lib/dl/slayer/neuron/adrf_iz.py                         208     83    60%   44-48, 169, 174, 179, 215-295, 384, 393, 403, 413, 418, 429, 467, 474-518, 521, 526, 551-560, 568, 571, 573, 648, 669-670
src/lava/lib/dl/slayer/neuron/alif.py                            172     69    60%   45, 153, 158, 191-262, 319, 329, 339, 349, 354, 360, 371, 408, 415-448, 451, 477-486, 494, 497, 589, 609-610
src/lava/lib/dl/slayer/neuron/base.py                             56     14    75%   136, 145-155, 196, 213, 217
src/lava/lib/dl/slayer/neuron/cuba.py                            118     40    66%   45, 133, 138, 157-188, 233, 243, 249, 260, 290, 297-315, 318, 338-341, 349, 360, 413, 433-434
src/lava/lib/dl/slayer/neuron/dropout.py                           7      2    71%   31-32
src/lava/lib/dl/slayer/neuron/dynamics/__init__.py                 4      0   100%
src/lava/lib/dl/slayer/neuron/dynamics/adaptive_phase_th.py       78     11    86%   29, 34, 39, 123, 212-223
src/lava/lib/dl/slayer/neuron/dynamics/adaptive_resonator.py     193    110    43%   27, 32, 37, 148, 238-262, 272-374, 441-525
src/lava/lib/dl/slayer/neuron/dynamics/adaptive_threshold.py      79     13    84%   29, 34, 39, 118, 207-226
src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.py       103     46    55%   28, 33, 38, 141-155, 164-207, 236-259
src/lava/lib/dl/slayer/neuron/dynamics/resonator.py              187    114    39%   27, 32, 37, 205-219, 221-235, 244-329, 381-467
src/lava/lib/dl/slayer/neuron/norm.py                             87     70    20%   38-51, 55, 60, 65-93, 140-159, 163-164, 169-170, 177, 182, 187-230
src/lava/lib/dl/slayer/neuron/rf.py                              153     32    79%   42-46, 149, 154, 159, 181-187, 190, 195, 203-204, 207, 299, 308, 319, 350, 358, 387, 392, 411-414, 422, 425, 427, 478, 499-500
src/lava/lib/dl/slayer/neuron/rf_iz.py                           156     54    65%   44-48, 153, 158, 163, 184-225, 303, 312, 323, 354, 361-388, 391, 396, 415-418, 426, 429, 431, 490, 511-512
src/lava/lib/dl/slayer/neuron/sigma_delta.py                      47     22    53%   31, 126, 140, 146, 151, 166-170, 190-220
src/lava/lib/dl/slayer/spike/__init__.py                           3      0   100%
src/lava/lib/dl/slayer/spike/complex.py                           33     12    64%   70-71, 75, 120-166
src/lava/lib/dl/slayer/spike/spike.py                             31     12    61%   16-21, 80-86, 116-121
src/lava/lib/dl/slayer/synapse/__init__.py                         3      0   100%
src/lava/lib/dl/slayer/synapse/complex.py                         58     31    47%   15-18, 23, 27-28, 32-33, 38, 44-49, 55-56, 61, 98-103, 160-166, 218-223, 282-288, 341-346
src/lava/lib/dl/slayer/synapse/layer.py                          206    175    15%   22-24, 28-29, 33-34, 39-50, 58, 65, 70, 109-142, 159-172, 234-295, 312-319, 376-436, 453-502, 567-628, 645-653, 709-768, 817-834
src/lava/lib/dl/slayer/utils/__init__.py                           6      0   100%
src/lava/lib/dl/slayer/utils/assistant.py                         99     91     8%   59-66, 80-82, 102-145, 165-203, 223-260
src/lava/lib/dl/slayer/utils/filter/__init__.py                    4      0   100%
src/lava/lib/dl/slayer/utils/filter/conv.py                       68     28    59%   27, 32, 37, 45, 64, 90-93, 124-131, 141-152, 158-165, 192, 220-223
src/lava/lib/dl/slayer/utils/filter/fir.py                        37     20    46%   41-49, 54, 78-93, 98-100, 110, 115, 120
src/lava/lib/dl/slayer/utils/int_utils.py                         15      4    73%   26, 43-44, 50
src/lava/lib/dl/slayer/utils/quantize.py                          11      1    91%   23
src/lava/lib/dl/slayer/utils/stats.py                            175    150    14%   37-45, 49-51, 56-59, 64-67, 72, 77, 81-93, 98-112, 131-134, 138-143, 147, 152-159, 185-213, 230-275, 286-330, 335
src/lava/lib/dl/slayer/utils/time/__init__.py                      4      0   100%
src/lava/lib/dl/slayer/utils/time/replicate.py                     6      3    50%   32-34
src/lava/lib/dl/slayer/utils/time/shift.py                        59     35    41%   24, 29, 34, 49-68, 74-91, 120-128, 135, 137
src/lava/lib/dl/slayer/utils/utils.py                             13      7    46%   35-45
--------------------------------------------------------------------------------------------
TOTAL                                                           4782   2596    46%

Required test coverage of 45.0% reached. Total coverage: 45.71%
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/file_baton.py:42: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
=============================================================================== 80 passed, 3 warnings in 353.02s (0:05:53) ================================================================================

**Comment by bamsumit** [comment]
@ahmetakman so you forced the unittest to stop after 5 minutes? The _first time_ you run it, it needs to compile all the cuda binaries so it can take a while. I don't see any failures in the log [here](https://github.com/lava-nc/lava-dl/issues/55#issuecomment-1075412542)

**Comment by ahmetakman** [comment]
Well , I have ran the same unit tests successfully before and it  approximately  took 2 minutes every time ( done that multiple times. )  . So it was not the first time. Also, I have waited more than 30 minutes just  before I did this ,and reproduced the error (hanging) to send here. Another point is, the computer resources become unused after 1.5 minutes and it waits infinitely.

**Comment by bamsumit** [comment]
So are you getting the hanging behavior on `tests/lava/lib/dl/slayer/utils/filter/test_conv_filter.py` consistently? 

If that's the case can you post the log of the following
```bash
cd tests/lava/lib/dl/slayer/utils/filter/
python -m unittest test_conv_filter.py
```

**Comment by ahmetakman** [comment]
Yeah that is correct 
Here it is = 
pytest -m unittest test_conv_filter.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/ahmetakman/lava-dl, configfile: pyproject.toml
plugins: cov-3.0.0
collected 2 items / 2 deselected                                                                                                                                                                          
/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/coverage/inorout.py:519: CoverageWarning: Module src/lava was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/coverage/control.py:793: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
WARNING: Failed to generate report: No data to report.

/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/pytest_cov/plugin.py:294: CovReportWarning: Failed to generate report: No data to report.

  self.cov_controller.finish()

============================================================================================ warnings summary =============================================================================================
../../../../../../../.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3
  /home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.8.10-final-0 -----------

==================================================================================== 2 deselected, 1 warning in 1.74s =====================================================================================

**Comment by bamsumit** [comment]
its `python -m unittest test_conv_filter.py` not __pytest__

**Comment by ahmetakman** [comment]
Sorry for the mistake ( it is quite late hours here ). 

I have corrected it and reran. Yes it is hanging. I have waited more than 20 minutes and observed resource usage no change occurs. When I interrupt I got this traceback which was essentially the same one in the objective of issue.
ython -m unittest test_conv_filter.py 
^CTraceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/ahmetakman/lava-dl/tests/lava/lib/dl/slayer/utils/filter/test_conv_filter.py", line 57, in test_conv
    out_cuda = conv(input.to(device), filter.to(device))
  File "/home/ahmetakman/lava-dl/src/lava/lib/dl/slayer/utils/filter/conv.py", line 194, in conv
    return _conv.apply(input, filter.flatten(), sampling_time)
  File "/home/ahmetakman/lava-dl/src/lava/lib/dl/slayer/utils/filter/conv.py", line 118, in forward
    return fwd(input, filter, sampling_time)
  File "/home/ahmetakman/lava-dl/src/lava/lib/dl/slayer/utils/filter/conv.py", line 80, in fwd
    return Accelerated.conv.fwd(
  File "/home/ahmetakman/lava-dl/src/lava/lib/dl/slayer/utils/utils.py", line 14, in __get__
    return staticmethod(self.fget).__get__(None, owner)()
  File "/home/ahmetakman/lava-dl/src/lava/lib/dl/slayer/utils/filter/conv.py", line 39, in conv
    Accelerated.module = load(
  File "/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1306, in _jit_compile
    baton.wait()
  File "/home/ahmetakman/lava-dl/.venv/lib/python3.8/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by bamsumit** [comment]
Okay. This looks like a known PyTorch issue. Can you try this fix https://github.com/zhou13/neurvps/issues/1#issuecomment-820898095 and see if it works?

**Comment by ahmetakman** [comment]
Oh, thanks. This seems the same issue. I have run the conv test and all unittests without a hanging issue. Now I am running the NMNIST training again (it seems it is working right now). I have got the first epoch right. So, I am closing the issue.
