### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr'

### ISSUE THREAD

**Issue by franzhd** [lava-nc/lava-dl#82]
Hello everyone, i have this error:
"No CUDA runtime is found, using CUDA_HOME='/usr' "

each time i import stuff from slayer like "import lava.lib.dl.slayer as slayer" . Asking torch.cuda.is_available() in a python3 shell inside the env does tell me that CUDA is available.
pytest pass all necessary steps.
Anyone has suggestion on how to resolve this problem? 
thanks for your attention!

Objective of issue:

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by bamsumit** [comment]
Can you post the outputs of these commands
```bash
nvidia-smi | grep CUDA
nvcc --version
python -c "import torch; print(torch.__version__)"
```

**Comment by franzhd** [comment]
![image](https://user-images.githubusercontent.com/58605124/173183372-6eb7109a-cf8e-4044-bb14-ebf286f0c4ea.png)

**Comment by bamsumit** [comment]
As long as `nvcc` and `torch` CUDA version match, it should be okay.

Can you try this:
1. Find cuda installation path: `which nvcc`
2. Make sure `<cuda_path>/home` exists (try `ls ...`)
3. `export CUDA_HOME=<cuda_path>/home`

and try running the unittests. `python -m unittest`

**Comment by bamsumit** [comment]
Hi @franzhd any progress?

**Comment by bamsumit** [comment]
Closed as STALE
