### ISSUE TITLE
Conda availability

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#90]
I was going to update to the new version of lava. I am curious whether lava-dl will be available to be installed from conda ? 

Objective of issue:

**Lava DL version:**

- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by bamsumit** [comment]
Hi @ahmetakman, yes lava-dl is available on conda: https://github.com/conda-forge/lava-dl-feedstock. I have not tried it personally though. I think Prof. Tobias Fischer is the maintainer of it.

**Comment by ahmetakman** [comment]
got it, thanks
