### ISSUE TITLE
Training deep SNNs with DECOLLE

### ISSUE THREAD

**Issue by nskat** [lava-nc/lava-dl#97]
Objective of issue:
Implementation of the training algorithm DECOLLE (Kaiser et al. 2020)

**Lava DL version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 
- [ ] bug report
- [x ] feature request
- [ ] documentation request

**Current behavior:**
Currently, only training with SLAYER is implemented and documented.

**Expected behavior:**
As per the desire of the developers to provide a general framework for neuromorphic computing, I believe that it would be great if Lava implemented training of deep SNNs via a variety of algorithms. In that sense, the naming of the training library (lava.lib.dl.slayer) would also benefit from evolving in future iterations, e.g. as lava.lib.dl.training. In the PR linked to this issue, I have implemented training of SNNs via DECOLLE. 

**Other information:**
A PR is linked to this issue.

**Comment by bamsumit** [comment]
@nskat closing this issue for now as we have not much progress on licensing situation.
