### ISSUE TITLE
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

### ISSUE THREAD

**Issue by Ajay-B-S** [lava-nc/lava-dl#99]
Hi
what is the cause of below issue during training. Need solution at the earliest. 

MyDataset is like this:

      event_d is EMG data of 1041 sets, each with 42000 samples (sampling rate of 700Hz and for 60s).  event_c is np.ones(42000) and event_t is (list(float_range(0, 59.976, '0.001428'))), 0 is the start , 59.976 is the stop and 0.001428 is the step.

        inputSpikes = slayer.io.Event(
                        event_d, None, event_c, event_t
                        ).to_tensor(sampling_time=self.samplingTime,
                                    dim= (2,2,self.nTimeBins)) #ajaybs#torch.zeros((2,1,2,self.nTimeBins))) (channels, height, width, time)

        desiredClass = torch.zeros((3, 1, 1, 1))
        desiredClass[label,...] = 1
        
        return inputSpikes, desiredClass

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [17], in <cell line: 3>()
      4 for i, (input, label) in enumerate(train_loader): # training loop
      5     input=input.float() 
----> 6     output = assistant.train(input, label)
      7 print(f'\r[Epoch {epoch:2d}/{epochs}] {stats}', end='')
      9 for i, (input, label) in enumerate(test_loader): # training loop

File /content/lava-dl/src/lava/lib/dl/slayer/utils/assistant.py:121, in Assistant.train(self, input, target)
    119 else:
    120     if self.lam is None:
--> 121         output = self.net(input)
    122     else:
    123         output, net_loss = self.net(input)

File /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

Input In [6], in Network.forward(self, spike)
     21 def forward(self, spike):
     22     for block in self.blocks:
---> 23         spike = block(spike)
     24     return spike

File /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /content/lava-dl/src/lava/lib/dl/slayer/block/base.py:518, in AbstractDense.forward(self, x)
    516     x = delay(x, 1)
    517 if self.delay is not None:
--> 518     x = self.delay(x)
    520 if self.count_log is True:
    521     return x, torch.mean(x > 0)

File /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /content/lava-dl/src/lava/lib/dl/slayer/axon/delay.py:144, in Delay.forward(self, input)
    140 broadcast_shape = list(input.shape[1:-1])
    141 broadcast_shape[0] = 1
    142 return _delayFunction.apply(
    143     input,
--> 144     self.delay.reshape(-1, 1, 1).repeat(broadcast_shape),
    145     self.grad_scale,
    146     self.sampling_time
    147 )

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

**Comment by mgkwill** [comment]
@bamsumit can you take a look at this?

**Comment by Ajay-B-S** [comment]
The issue was this dim of input and label. With corrected dim, the issue is not seen
